show_ticks       = yes
show_tick_labels = yes

<ticks>
radius       = dims(ideogram,radius_outer) + 0.005r
label_offset = 12p
multiplier = 1e-6 # to convert to Mbp
color        = black


<tick>
spacing    = 10000
size       = 10p
thickness  = 2p
show_label = no
label_size = 18p
</tick>

<tick>
spacing    = 200000
size       = 35p
thickness  = 5p
show_label = yes
label_size = 25p
format = %.1f Mb
</tick>
</ticks>
